[project]
name = "santa-tracker"
version = "0.1.0"
description = "A simple bot to track Santa's location"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "pytest>=9.0.2",
]

[dependency-groups]
dev = [
    "pytest>=9.0.2",
]
